# Generated by Django 3.2.12 on 2022-03-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variavel',
            options={'verbose_name': 'variavel', 'verbose_name_plural': 'variaveis'},
        ),
    ]
